# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- alembic-jekyll-theme.gemspec
- .jekyll-cache

# 2. Installed Gems
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji

# 3. Gem settings
paginate: 5 # jekyll-paginate > items per page
paginate_path: /page:num # jekyll-paginate > blog page
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
twitter:
  username: CoffeeGenos # jekyll-seo-tag > Owners twitter username
author: Charlie Tizzard # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: Charlie Tizzard # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://twitter.com/CoffeeGenos
    - https://www.linkedin.com/in/charles-tizzard/
    - https://github.com/8BitSensei
# markdown: CommonMark # Markdown parse settings, CommonMark performs slightly better an others in build time
# commonmark:
  # options: ["SMART", "FOOTNOTES"]
  # extensions: ["strikethrough", "autolink", "table"]

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/London # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    title: Home # Needed for Siteleaf
    output: true
    description: "Programming, History, Cooking, agus cúpla focal" # The post list page content

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
    values:
      image: "/assets/default-social-image.png" # Default image for sharing

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: en-GB # Set the site language
title: "Charlie Tizzard Ó Kevlahan" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/logo-medium.svg" # Site logo, also used in jekyll-seo-tag
description: "One year fresh CS graduate working as a backend Engineer in C# and .NET on fintech. 
My interests are in History, Medieval Literature, Cooking, and the Irish Language, I specialise in Late Iron Age
to Early Medieval Britain and Ireland. Talk to me about Dependency Injection, Romano-Celtic temple sites, and Immacallam Choluim Cille ⁊ ind óclaig." # Site description and default description, also used in jekyll-seo-tag
url: "https://charietizzard.co.uk" # Site url, also used in jekyll-seo-tag
baseurl: ""
repo: "https://github.com/8BitSensei"
email: ctizzard@outlook.com"
# disqus: "alembic-1" # Blog post comments, uncomment the option and set the site ID from your Disqus account
avatarurl: "/assets/favicons/logo-tiny.png" # Uses avatars for favicons to get multple sites, eg Gravatar, Twitter, GitHub
# google_analytics: ''
# service_worker: false # Will turn off the service worker if set to false
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

# 8. Site navigation
navigation_header:
  Home: /
  About Me: /elements/
  Search: /search/

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  Twitter: https://twitter.com/CoffeeGenos
  LinkedIn: https://www.linkedin.com/in/charles-tizzard/
  GitHub: https://github.com/8BitSensei
  link: https://charlietizzard.co.uk
  RSS: /feed.xml

sharing_links: # Appear at the bottom of single blog posts, uncomment and comment out as desired. Colours set the button colour
  Twitter: "#0d94e7"
  facebook: "#3B5998"
  # Google+: "#DC4E41"
  # Pinterest: "#BD081C"
  LinkedIn: "#0077B5"
  # tumblr: "#36465D"
  # Reddit: "#FF4500"
  # Hacker News: "#ff6600"
  # Designer News: "#2D72D9"
  Email: ""
